model: 
  model_name: vit_base
  pretrained_type: best_model.pth

data:
  dataset_name: cifar10

train:
  epochs: 60
  batch_size: 128
  label_smoothing: 0.1
  lr: 0.1
  lr_decay: 0.995
  momentum: 0.9
  weight_decay: 0.0001
  betas: (0.9, 0.999)
  gamma: 0.1
  milestones: [16, 32]
  lambda_decay: 0.998466
  optimizer: SGD
  scheduler: multisteplr  
  resume: False